### ISSUE TITLE
Showing the user defined icons for each node

### ISSUE THREAD

**Issue by hayagur** [eliftech/treeview-react-bootstrap#7]
It would be very helpful if the feature of icon per node was working.
In the old project, the user could define, for example the following:
_nodes: [
  {
 text : 'my text',
 icon:'glyphicon glyphicons-glass'
 }_

But in the current project it shows a checkbox if options.selectable=true or nothing if options.selectable=false.

The fix should be very simple:
1. After line 59 add:
   **icon: childNode.icon**
2. Before line 344 add:
   **if(this.props.options.selectable)**
3. In line 404 replace:
   **let nodeIcon = this.props.options.selectable ?**
   with:
   **let nodeIcon = (node.icon || options.nodeIcon) ?**

Then the user can get his own icons, when he creates the following component:
`<TreeView data={tree} collapseIcon={'glyphicon glyphicon-collapse-down'} selectable={false} nodeIcon={'glyphicon'}/>`

**Comment by kingr** [comment]
None of the options besides 'Text' works.

**Comment by hayagur** [comment]
I've realized non of them are working, but why not enable them, if it is so easy to do so?

**Comment by NazarHopchak** [comment]
Added the possibility to show user defined icons.
Thanks for your contribution
